#!/bin/bash

echo -e "\033[5m\033[32m\033[44m\033[1mCoucou les correcteurs\033[1m\033[0m \n"
echo -e "\033[5m\033[32m\033[44m\033[1mD'abord le bundle install\033[1m\033[0m \033[0m\033[0m \n"
bundle install --without production
bundle exec rails webpacker:install
yarn add jquery
yarn add leaflet
echo -e "\033[5m\033[32m\033[44m\033[1mLe programme va lancer le migrate\033[1m\033[0m \033[0m\033[m \n"
rails db:migrate

